[tool.isort]
profile = "black"
extend_skip = ["debug", "tests", "examples"]

[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
exclude = '''
/(
  | debug
  | docs
  | examples
  | tests
)/
'''
